language: android  
jdk: oraclejdk7
# sudo: required
# env:
  # global:
    # Add this
    # - MALLOC_ARENA_MAX=2
    # - ADB_INSTALL_TIMEOUT=10
notifications:
  email: true

android:  
  components:
    - build-tools-23.0.3
    - android-23
    - extra-android-m2repository
    - extra-android-support
# git:  
#   submodules: false
before_install:  
  # - java -Xmx1024m -version
  # - javac -J-Xmx1024m -version
  # - ulimit -s 1082768
  - chmod +x gradlew
  - echo y | android update sdk --no-ui --all --filter tool,extra-android-m2repository,extra-android-support,extra-google-google_play_services,extra-google-m2repository,android-23
  - echo y | android update sdk --no-ui --all --filter build-tools-23.0.3
#   - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
#   - git submodule init && git submodule update
script:  
  - ./gradlew assembleRelease -PdisablePreDex --stacktrace
before_deploy:  
  - mv "app/build/outputs/apk/app-$TRAVIS_TAG-release.apk" "app/build/outputs/apk/zhihu.apk"
deploy:  
  provider: releases
  api_key: "9736ac63ffcc8aa654543dee348bfaf3b424fcb5"
  file: app/build/outputs/apk/zhihu.apk
  skip_cleanup: true
  on:
    tags: true